# Generated by Django 5.0.7 on 2024-09-21 20:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_alter_address_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_token', models.CharField()),
                ('order_placed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_process_date', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('transaction_status', models.CharField(null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paid', models.BooleanField(null=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_code', models.CharField(null=True)),
                ('shipping_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('billing_date', models.DateField()),
                ('transaction_status', models.CharField(null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paid', models.BooleanField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
