# Generated by Django 5.0.7 on 2024-10-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product_sku', models.CharField(max_length=30)),
                ('product_name', models.CharField(default='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_size', models.CharField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount_code', models.CharField(max_length=20)),
            ],
        ),
    ]
