# Generated by Django 5.0.7 on 2024-08-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacterialMarker',
            fields=[
                ('bacterial_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('bacterial_marker_name', models.CharField()),
                ('bacterial_marker_code', models.CharField()),
            ],
            options={
                'db_table': 'bacterial_marker',
            },
        ),
        migrations.CreateModel(
            name='BacterialMarkerSpecialCase',
            fields=[
                ('bacterial_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('bacterial_marker_name', models.CharField()),
                ('bacterial_marker_code', models.CharField()),
                ('function_type', models.CharField()),
                ('delivery_type', models.CharField()),
            ],
            options={
                'db_table': 'bacterial_marker_special_case',
            },
        ),
        migrations.CreateModel(
            name='FluoresceneMarker',
            fields=[
                ('fluorescene_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('fluorescene_marker_name', models.CharField()),
                ('fluorescene_marker_code', models.CharField()),
            ],
            options={
                'db_table': 'fluorescene_marker',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_number', models.IntegerField()),
                ('gene_name', models.CharField()),
                ('symbol', models.CharField()),
                ('locus_id', models.IntegerField()),
                ('species', models.CharField()),
                ('description', models.CharField()),
                ('target_sequence', models.CharField()),
                ('reference_link', models.CharField()),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField()),
                ('loaded', models.BooleanField()),
                ('currency', models.CharField()),
                ('manufacturer', models.CharField()),
            ],
            options={
                'db_table': 'product_inventory',
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('promoter_id', models.AutoField(primary_key=True, serialize=False)),
                ('promoter_name', models.CharField()),
                ('promoter_code', models.CharField()),
            ],
            options={
                'db_table': 'promoter',
            },
        ),
        migrations.CreateModel(
            name='PromoterSpecialCase',
            fields=[
                ('promoter_id', models.AutoField(primary_key=True, serialize=False)),
                ('promoter_name', models.CharField()),
                ('promoter_code', models.CharField()),
                ('function_type', models.CharField()),
                ('delivery_type', models.CharField()),
            ],
            options={
                'db_table': 'promoter_special_case',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField()),
                ('property_code', models.CharField()),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='ProteinTag',
            fields=[
                ('protein_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('protein_tag_name', models.CharField()),
                ('protein_tag_code', models.CharField()),
            ],
            options={
                'db_table': 'protein_tag',
            },
        ),
        migrations.CreateModel(
            name='SelectionMarker',
            fields=[
                ('selection_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_marker_name', models.CharField()),
                ('selection_marker_code', models.CharField()),
            ],
            options={
                'db_table': 'selection_marker',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sku', models.CharField()),
                ('product_name', models.CharField()),
                ('function_category', models.CharField()),
                ('function_type_code', models.CharField()),
                ('delivery_type_code', models.CharField()),
                ('serial_id', models.CharField()),
                ('promoter_code', models.CharField()),
                ('property_code', models.CharField()),
                ('protein_tag_code', models.CharField()),
                ('fluorescene_marker_code', models.CharField()),
                ('selection_marker_code', models.CharField()),
                ('bacterial_marker_code', models.CharField()),
                ('delivery_format', models.CharField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('load_status', models.CharField(blank=True, default='Loaded', null=True)),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.gene')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productinventory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
