# Generated by Django 5.0.7 on 2024-08-05 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_functiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLibrary',
            fields=[
                ('delivery_library_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_type_symbol', models.CharField()),
                ('delivery_type_name', models.CharField()),
                ('delivery_format_symbol', models.CharField()),
                ('delivery_format_name', models.CharField()),
                ('function_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.functiontype')),
            ],
            options={
                'db_table': 'delivery_library',
            },
        ),
    ]
