# Generated by Django 5.0.7 on 2024-08-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_deliverylibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacterialmarkerspecialcase',
            old_name='delivery_type',
            new_name='delivery_type_name',
        ),
        migrations.RenameField(
            model_name='promoterspecialcase',
            old_name='delivery_type',
            new_name='delivery_type_name',
        ),
        migrations.RenameField(
            model_name='promoterspecialcase',
            old_name='function_type',
            new_name='function_type_name',
        ),
        migrations.RemoveField(
            model_name='bacterialmarkerspecialcase',
            name='function_type',
        ),
    ]
