# Generated by Django 5.0.7 on 2024-08-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_delivery_type_bacterialmarkerspecialcase_delivery_type_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacterialmarkerspecialcase',
            old_name='delivery_type_name',
            new_name='delivery_type_symbol',
        ),
        migrations.RenameField(
            model_name='promoterspecialcase',
            old_name='delivery_type_name',
            new_name='delivery_type_symbol',
        ),
        migrations.RenameField(
            model_name='promoterspecialcase',
            old_name='function_type_name',
            new_name='function_type_symbol',
        ),
    ]
