# Generated by Django 5.0.7 on 2024-08-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_delivery_type_name_bacterialmarkerspecialcase_delivery_type_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterspecialcase',
            name='delivery_type_symbol',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='promoterspecialcase',
            name='function_type_symbol',
            field=models.CharField(null=True),
        ),
        migrations.AddConstraint(
            model_name='promoterspecialcase',
            constraint=models.CheckConstraint(check=models.Q(('function_type_symbol__isnull', False), ('delivery_type_symbol__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
