# Generated by Django 5.0.7 on 2024-08-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_delivery_format_product_delivery_format_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='function_category',
        ),
    ]
