# Generated by Django 5.0.7 on 2024-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_deliveryformat_table_alter_functiontype_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type_code', models.CharField()),
                ('delivery_format_code', models.CharField()),
                ('ready_status', models.CharField()),
                ('amount', models.CharField()),
                ('unit_size', models.CharField()),
                ('discount_code', models.CharField(null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField()),
            ],
            options={
                'db_table': 'design_library',
            },
        ),
    ]
