# Generated by Django 5.0.7 on 2024-08-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_structuretype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylibrary',
            name='delivery_format_name',
        ),
        migrations.RemoveField(
            model_name='deliverylibrary',
            name='structure_type_name',
        ),
    ]
