# Generated by Django 5.0.7 on 2024-07-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacterialMarker',
            fields=[
                ('bacterial_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('bacterial_marker_name', models.CharField()),
                ('bacterial_marker_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='BacterialMarkerSpecialCase',
            fields=[
                ('bacterial_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('bacterial_marker_name', models.CharField()),
                ('bacterial_marker_code', models.CharField()),
                ('function_type', models.CharField()),
                ('delivery_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FluoresceneMarker',
            fields=[
                ('fluorescene_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('fluorescene_marker_name', models.CharField()),
                ('fluorescene_marker_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_number', models.IntegerField()),
                ('gene_name', models.CharField()),
                ('symbol', models.CharField()),
                ('locus_id', models.IntegerField()),
                ('species', models.CharField()),
                ('description', models.CharField()),
                ('target_sequence', models.CharField()),
                ('reference_link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField()),
                ('loaded', models.BooleanField()),
                ('currency', models.CharField()),
                ('manufacturer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('promoter_id', models.AutoField(primary_key=True, serialize=False)),
                ('promoter_name', models.CharField()),
                ('promoter_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoterSpecialCase',
            fields=[
                ('promoter_id', models.AutoField(primary_key=True, serialize=False)),
                ('promoter_name', models.CharField()),
                ('promoter_code', models.CharField()),
                ('function_type', models.CharField()),
                ('delivery_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField()),
                ('property_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinTag',
            fields=[
                ('protein_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('protein_tag_name', models.CharField()),
                ('protein_tag_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectionMarker',
            fields=[
                ('selection_marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_marker_name', models.CharField()),
                ('selection_marker_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sku', models.CharField()),
                ('product_name', models.CharField()),
                ('function_type', models.CharField()),
                ('structure_type', models.CharField()),
                ('delivery_type', models.CharField()),
                ('promoter_name', models.CharField()),
                ('property_name', models.CharField()),
                ('protein_tag_name', models.CharField()),
                ('fluorescene_marker_name', models.CharField()),
                ('selection_marker_name', models.CharField()),
                ('bacterial_marker_name', models.CharField()),
                ('delivery_format', models.CharField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.gene')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productinventory')),
            ],
        ),
    ]
