# Generated by Django 5.0.7 on 2024-08-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('function_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(unique=True)),
                ('function_type_name', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('load_status', models.CharField(blank=True, default='Loaded', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory')),
            ],
            options={
                'db_table': 'function_type',
            },
        ),
    ]
