# Generated by Django 5.0.7 on 2024-08-10 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_promoterspecialcase_delivery_type_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneLibrary',
            fields=[
                ('gene_library_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_number', models.IntegerField()),
                ('gene_name', models.CharField()),
                ('symbol', models.CharField()),
                ('locus_id', models.IntegerField()),
                ('species', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('target_sequence', models.CharField(blank=True)),
                ('reference_link', models.CharField(null=True)),
            ],
            options={
                'db_table': 'gene_library',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.genelibrary'),
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
    ]
