# Generated by Django 5.0.7 on 2024-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_genelibrary_alter_product_gene_delete_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genelibrary',
            name='target_sequence',
            field=models.CharField(blank=True, default=''),
        ),
    ]
