# Generated by Django 5.0.7 on 2024-08-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_function_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_format_description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
