# Generated by Django 5.0.7 on 2024-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_format_symbol', models.CharField()),
                ('delivery_format_name', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_format_description',
        ),
    ]
