# Generated by Django 5.0.7 on 2024-08-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_deliveryformat_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryformat',
            table='delivery_formats',
        ),
        migrations.AlterModelTable(
            name='functiontype',
            table='function_types',
        ),
    ]
