# Generated by Django 5.0.7 on 2024-08-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_deliverylibrary_delivery_format_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functiontype',
            old_name='symbol',
            new_name='function_type_symbol',
        ),
    ]
