# Generated by Django 5.0.7 on 2024-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_genelibrary_target_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelibrary',
            name='gene_number',
        ),
        migrations.AlterField(
            model_name='genelibrary',
            name='target_sequence',
            field=models.CharField(),
        ),
    ]
