# Generated by Django 5.0.7 on 2024-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_genelibrary_gene_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery_format',
            new_name='delivery_format_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='load_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_weight',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_code',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ready_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genelibrary',
            name='locus_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genelibrary',
            name='species',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='genelibrary',
            name='target_sequence',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterModelTable(
            name='bacterialmarker',
            table='bacterial_markers',
        ),
        migrations.AlterModelTable(
            name='bacterialmarkerspecialcase',
            table='bacterial_markers_special_case',
        ),
        migrations.AlterModelTable(
            name='fluorescenemarker',
            table='fluorescene_markers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='promoter',
            table='promoters',
        ),
        migrations.AlterModelTable(
            name='promoterspecialcase',
            table='promoters_special_case',
        ),
        migrations.AlterModelTable(
            name='proteintag',
            table='protein_tags',
        ),
        migrations.AlterModelTable(
            name='selectionmarker',
            table='selection_markers',
        ),
    ]
